# Generated by Django 4.1.5 on 2023-01-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
        ("Contract", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_client",
                to="Client.client",
            ),
        ),
    ]
