# Generated by Django 4.1.5 on 2023-01-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0005_alter_client_sales_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Contract", "0002_alter_contract_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_client",
                to="Client.client",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sales_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
