# Generated by Django 4.1.5 on 2023-01-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="compagny_name", new_name="company_name",
        ),
    ]
