# Generated by Django 4.1.5 on 2023-01-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="User.team"
            ),
            preserve_default=False,
        ),
    ]
