# Generated by Django 4.1.5 on 2023-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team",
            field=models.CharField(
                choices=[
                    ("SUPPORT", "support"),
                    ("SALES", "sales"),
                    ("ADMIN", "admin"),
                ],
                max_length=7,
            ),
        ),
    ]
